### PR TITLE
Update omotes-simulator-core to latest release, 

### PR DESCRIPTION
**Pull request by MichielTukker**
integrated progress function, fixed package references

### CODE REVIEW

**Comment by MichielTukker** [comment]
Fixes #27  and #28

**Comment by lfse-slafleur** [comment]
@MichielTukker  Test failed in case you didn't receive the notification.

**Comment by MichielTukker** [comment]
> @MichielTukker Test failed in case you didn't receive the notification.

I noticed,  but I'm trying to figure out why as it works locally....

**Comment by MichielTukker** [comment]
@MarkTNO   We're using OpenJDK 17  for Rosim,  is that the right version?  (the tests in omotes-simulator-core run fine with that version)

**Comment by lfse-slafleur** [comment]
> @MarkTNO We're using OpenJDK 17 for Rosim, is that the right version? (the tests in omotes-simulator-core run fine with that version)

Definitely Mark can help provide a clear answer here. However, as a side note, most JAR's contain the correct version of Java to run and newer JVM's are backward compatible. So if it is too new, that shouldn't necessarily create an issue.

**Comment by MarkTNO** [comment]
Rosim is being developed with java 17, so that should be fine anyway.

**Pull request merged**
